#
# APPLICATION CONFIG
#

# DAO (PersistenceExceptionTranslationAutoConfiguration)
# needed as a workaround for spring-boot 1.2+
spring:
  dao:
    exceptiontranslation:
      enabled: false

# enable gz compression
server:
  compression:
    enabled: true
