#
# APPLICATION CONFIG
#

# enable gz compression
server:
  compression:
    enabled: true

app:
  # this value is the OAuth 2.0 client ID for your application
  clientId: id
  # this value is the OAuth 2.0 shared secret for your application
  clientSecret: secret
  # redirectUri must end with /verify
  redirectUri: http://localhost:8080/verify

# ELASTICSEARCH (ElasticsearchProperties})
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
